// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/le-sita": {
    params: {};
  };
  "/editions": {
    params: {};
  };
  "/editions/malabo-2020": {
    params: {};
  };
  "/editions/djibouti-2021": {
    params: {};
  };
  "/editions/lome-2022": {
    params: {};
  };
  "/editions/conakry-2023": {
    params: {};
  };
  "/exposants": {
    params: {};
  };
  "/formations": {
    params: {};
  };
  "/presse": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/le-sita" | "/editions" | "/editions/malabo-2020" | "/editions/djibouti-2021" | "/editions/lome-2022" | "/editions/conakry-2023" | "/exposants" | "/formations" | "/presse" | "/contact";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/le-sita" | "/editions" | "/editions/malabo-2020" | "/editions/djibouti-2021" | "/editions/lome-2022" | "/editions/conakry-2023" | "/exposants" | "/formations" | "/presse" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/le-sita.tsx": {
    id: "routes/le-sita";
    page: "/le-sita";
  };
  "routes/editions/index.tsx": {
    id: "routes/editions/index";
    page: "/editions";
  };
  "routes/editions/malabo-2020.tsx": {
    id: "routes/editions/malabo-2020";
    page: "/editions/malabo-2020";
  };
  "routes/editions/djibouti-2021.tsx": {
    id: "routes/editions/djibouti-2021";
    page: "/editions/djibouti-2021";
  };
  "routes/editions/lome-2022.tsx": {
    id: "routes/editions/lome-2022";
    page: "/editions/lome-2022";
  };
  "routes/editions/conakry-2023.tsx": {
    id: "routes/editions/conakry-2023";
    page: "/editions/conakry-2023";
  };
  "routes/exposants.tsx": {
    id: "routes/exposants";
    page: "/exposants";
  };
  "routes/formations.tsx": {
    id: "routes/formations";
    page: "/formations";
  };
  "routes/presse.tsx": {
    id: "routes/presse";
    page: "/presse";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/le-sita": typeof import("./app/routes/le-sita.tsx");
  "routes/editions/index": typeof import("./app/routes/editions/index.tsx");
  "routes/editions/malabo-2020": typeof import("./app/routes/editions/malabo-2020.tsx");
  "routes/editions/djibouti-2021": typeof import("./app/routes/editions/djibouti-2021.tsx");
  "routes/editions/lome-2022": typeof import("./app/routes/editions/lome-2022.tsx");
  "routes/editions/conakry-2023": typeof import("./app/routes/editions/conakry-2023.tsx");
  "routes/exposants": typeof import("./app/routes/exposants.tsx");
  "routes/formations": typeof import("./app/routes/formations.tsx");
  "routes/presse": typeof import("./app/routes/presse.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
};